## Production ConfigMap for ML Platform
# Purpose: Environment-specific non-secret overrides for production
# Notes:
# - Overrides base ConfigMap; only include values that differ in prod

apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-platform-config-production
  namespace: ml-platform-production
data:
  ML_ENV: "production"
  ML_LOG_LEVEL: "INFO"
  ML_LOG_FORMAT: "json"
  ML_TRACING_ENABLED: "true"
  ML_GPU_PREFERENCE: "auto"
  ML_MAX_BATCH_SIZE: "512"
  ML_JWT_ALGORITHM: "HS256"
  ML_JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ML_MODEL_DEFAULT_NAME: "curve_forecaster"
  ML_EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  ML_INGEST_QUEUE: "embeddings_rebuild"
  ML_MODEL_SERVING_PORT: "9005"
  ML_EMBEDDING_PORT: "9006"
  ML_SEARCH_PORT: "9007"
  ML_VECTOR_POOL_SIZE: "20"
  ML_VECTOR_MAX_QUERIES: "100000"
  ML_VECTOR_COMMAND_TIMEOUT: "120"
  ML_MODEL_CACHE_SIZE: "1000"
  ML_SEARCH_CACHE_SIZE: "10000"
  ML_EMBEDDING_CACHE_TTL: "3600"
  ML_RESULT_CACHE_TTL: "600"
  ML_PROMETHEUS_METRICS_ENABLED: "true"
  ML_OTEL_SERVICE_NAME: "ml-platform-production"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-platform-config-blue
  namespace: ml-platform-blue
data:
  ML_ENV: "production-blue"
  ML_LOG_LEVEL: "INFO"
  ML_LOG_FORMAT: "json"
  ML_TRACING_ENABLED: "true"
  ML_GPU_PREFERENCE: "auto"
  ML_MAX_BATCH_SIZE: "512"
  ML_JWT_ALGORITHM: "HS256"
  ML_JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ML_MODEL_DEFAULT_NAME: "curve_forecaster"
  ML_EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  ML_INGEST_QUEUE: "embeddings_rebuild_blue"
  ML_MODEL_SERVING_PORT: "9005"
  ML_EMBEDDING_PORT: "9006"
  ML_SEARCH_PORT: "9007"
  ML_OTEL_SERVICE_NAME: "ml-platform-blue"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-platform-config-green
  namespace: ml-platform-green
data:
  ML_ENV: "production-green"
  ML_LOG_LEVEL: "INFO"
  ML_LOG_FORMAT: "json"
  ML_TRACING_ENABLED: "true"
  ML_GPU_PREFERENCE: "auto"
  ML_MAX_BATCH_SIZE: "512"
  ML_JWT_ALGORITHM: "HS256"
  ML_JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ML_MODEL_DEFAULT_NAME: "curve_forecaster"
  ML_EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  ML_INGEST_QUEUE: "embeddings_rebuild_green"
  ML_MODEL_SERVING_PORT: "9005"
  ML_EMBEDDING_PORT: "9006"
  ML_SEARCH_PORT: "9007"
  ML_OTEL_SERVICE_NAME: "ml-platform-green"
