## Production Secrets for ML Platform
# Purpose: Store sensitive config for production (managed securely)
# Notes:
# - Prefer sealed-secrets or external secret managers in real deployments
# - Ensure RBAC restricts access appropriately

apiVersion: v1
kind: Secret
metadata:
  name: ml-platform-secrets-production
  namespace: ml-platform-production
type: Opaque
stringData:
  # Production database connection
  ML_VECTOR_DB_DSN: "postgresql://mlflow:${POSTGRES_PASSWORD}@postgres-ha-postgresql:5432/mlflow"
  
  # Production Redis cluster
  ML_REDIS_URL: "redis://redis-cluster:6379"
  
  # Production MinIO
  ML_MINIO_ENDPOINT: "https://minio-ha:9000"
  ML_MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  ML_MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
  
  # Service URLs
  ML_EMBEDDING_SERVICE_URL: "http://embedding-service-active:9006"
  ML_SEARCH_SERVICE_URL: "http://search-service-active:9007"
  
  # Security
  ML_JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  
  # Observability
  ML_OTEL_EXPORTER: "http://jaeger-collector:14268/api/traces"
  
  # Vault integration
  VAULT_ADDR: "https://vault.254carbon.internal:8200"
  VAULT_TOKEN: "${VAULT_SERVICE_TOKEN}"

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: ml-platform-production
spec:
  provider:
    vault:
      server: "https://vault.254carbon.internal:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ml-platform-vault-secrets
  namespace: ml-platform-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: ml-platform-vault-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: ml-platform/database/postgres
      property: password
  - secretKey: minio-access-key
    remoteRef:
      key: ml-platform/shared/minio
      property: access_key
  - secretKey: minio-secret-key
    remoteRef:
      key: ml-platform/shared/minio
      property: secret_key
  - secretKey: jwt-secret-key
    remoteRef:
      key: ml-platform/shared/jwt
      property: secret_key
  - secretKey: encryption-key
    remoteRef:
      key: ml-platform/shared/encryption
      property: key
