## Shared ConfigMap for ML Platform (base)
# Purpose: Centralize non-secret configuration consumed by services
# Notes:
# - Values are safe for config; secrets must live in Secret resources
# - Overlays may override keys per environment

apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-platform-config
  namespace: ml-platform
data:
  ML_ENV: "production"
  ML_LOG_LEVEL: "INFO"
  ML_LOG_FORMAT: "json"
  ML_TRACING_ENABLED: "true"
  ML_GPU_PREFERENCE: "auto"
  ML_MAX_BATCH_SIZE: "256"
  ML_JWT_ALGORITHM: "HS256"
  ML_JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ML_MODEL_DEFAULT_NAME: "curve_forecaster"
  ML_EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  ML_INGEST_QUEUE: "embeddings_rebuild"
  ML_MODEL_SERVING_PORT: "9005"
  ML_EMBEDDING_PORT: "9006"
  ML_SEARCH_PORT: "9007"
  ML_MLFLOW_PORT: "5000"
  # Feature flags
  ML_AUTH_ENABLED: "false"
  ML_AB_TESTING_ENABLED: "false"
  ML_VECTOR_BACKEND: "pgvector"
  # OpenSearch configuration (when ML_VECTOR_BACKEND=opensearch)
  ML_OPENSEARCH_HOSTS: "http://opensearch:9200"
  ML_OPENSEARCH_INDEX: "ml_embeddings"
  ML_OPENSEARCH_VERIFY_CERTS: "false"
  ML_VECTOR_DIMENSION: "384"
