## Kubernetes manifests for Search Service (base)
# Purpose: Deployment, Service, and HPA for search-service
# Notes:
# - Depends on embedding-service for semantic queries
# - Probes target /health on port 9007
# - Env from ConfigMap/Secret: ml-platform-config, ml-platform-secrets
# - HPA targets CPU/memory; adjust for typical query mix

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: ml-platform
  labels:
    app: search-service
    service: search-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
        service: search-service
    spec:
      containers:
      - name: search-service
        image: ghcr.io/254carbon/ml-platform-search:latest
        ports:
        - containerPort: 9007
          name: http
        env:
        - name: ML_SEARCH_PORT
          value: "9007"
        envFrom:
        - configMapRef:
            name: ml-platform-config
        - secretRef:
            name: ml-platform-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9007
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9007
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: ml-platform
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
  - name: http
    port: 9007
    targetPort: 9007
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: search-service-hpa
  namespace: ml-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-service
  minReplicas: 3
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
